version: "3.9"
services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    # environment:
    #  - POSTGRES_USER=henry
    #  - POSTGRES_PASSWORD=password
    #  - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - secrets.env
    volumes:
      - mount:/var/lib/postgresql/data
    networks:
      - postgresnetwork
    ports:
      - 8897:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    # environment:
    #  - PGADMIN_DEFAULT_EMAIL=henry@henry.com
    #  - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    networks:
      - postgresnetwork
networks:
  postgresnetwork:
volumes:
  mount: